using System;
using System.Windows;

namespace FileDownloader
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        private FileClient fileDownloader;

        public MainWindow()
        {
            InitializeComponent();

            fileDownloader = new FileClient();
            
            if (fileDownloader.Run())
            {
                fileDownloader.CheckServer(true);
            }

            //todo принимаем список файлов и размеров - DONE
            //todo написать конвертер
            //todo отправляем запрос на файл
            //todo загружаем файл 
            //todo и обновляем прогресс бар
            //todo сообщение об окончании загрузки
            // https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.backgroundworker?redirectedfrom=MSDN&view=net-5.0
        }

        private void UpdateButton_OnClick(object sender, RoutedEventArgs e)
        {
            fileDownloader.CheckServer(false);

            dataGrid.AutoGeneratedColumns += datagrid1_AutoGeneratedColumns;

            dataGrid.ItemsSource = fileDownloader.GetFileList();
        }

        void datagrid1_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dataGrid.Columns[0].Header = "Имя файла (Мб)";
            dataGrid.Columns[1].Header = "Размер файла";
        }

        private void DownloadButton_OnClick(object sender, RoutedEventArgs e)
        {
            throw new NotImplementedException();
        }

        private void QuitButton_OnClick(object sender, RoutedEventArgs e)
        {
            fileDownloader.Quit();
            Application.Current.Shutdown();
        }
    }
}
